export const DEFAULT_REFERENCE_SCREEN_WIDTH = 375;
export const DEFAULT_REFERENCE_SCREEN_HEIGHT = 812;

export const LOCATION_DELTA = {
  latitudeDelta: 0.0203,
  longitudeDelta: 0.0203,
};

export const DEFAULT_PHONE_NUM_PREFIX = '84';

export const DEFAULT_USER_MARK_POINT_ANIMATION_DURATION = 1000;

export const RADIUS_TO_GET_NEARBY_TERRY = 20000;

export const DISTANCE_THRESHOLD_TO_RE_GET_NEARBY_TERRY = 5000;
