export enum EErrorCode {
  UNKNOWN_ERROR = 'GEOTERRY_ERROR_0000',
  INVALID_TOKEN = 'GEOTERRY_ERROR_0001',
  PROFILE_NOT_FOUND = 'GEOTERRY_ERROR_0002',
  FORBIDDEN_PROFILE_ACCESS = 'GEOTERRY_ERROR_0003',
  INCORRECT_OTP = 'GEOTERRY_ERROR_0004',
  ALREADY_ONBOARD_IDENTIFIER = 'GEOTERRY_ERROR_0005',
  INCORRECT_PASSWORD = 'GEOTERRY_ERROR_0006',
  UPLOAD_FILE_FAILED = 'GEOTERRY_ERROR_0007',
  SIZE_IMAGE_NOT_ACCEPTED = 'GEOTERRY_ERROR_0008',
  FAILED_TO_REFRESH_TOKEN = 'GEOTERRY_ERROR_0009',
  DUPLICATED_NAME = 'GEOTERRY_ERROR_0010',
  DUPLICATED_SLUG = 'GEOTERRY_ERROR_0011',
  ALREADY_ONBOARD_PROFILE = 'GEOTERRY_ERROR_0012',
  CANNOT_GENERATE_QR_CODE = 'GEOTERRY_ERROR_0013',
  INVALID_TERRY = 'GEO_TERRY_ERROR_0014',
  OUT_OF_DISTANCE = 'GEO_TERRY_ERROR_0015',
}

export enum EStatusCode {
  SUCCESS = 200,
  BAD_REQUEST = 400,
  FORBIDEN = 403,
}
