export enum ENavigationScreen {
  ONBOARDING_SCREEN = 'ONBOARDING_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN',
  REGISTER_SCREEN = 'REGISTER_SCREEN',
  OTP_SCREEN = 'OTP_SCREEN',
  LOADING_MODAL = 'LOADING_MODAL',
  HOME_SCREEN = 'HOME_SCREEN',
}
