export enum ENavigationScreen {
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  ONBOARDING_SCREEN = 'ONBOARDING_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN',
  REGISTER_SCREEN = 'REGISTER_SCREEN',
  OTP_SCREEN = 'OTP_SCREEN',
  LOADING_MODAL = 'LOADING_MODAL',
  CREATE_PROFILE_NAVIGATOR = 'CREATE_PROFILE_NAVIGATOR',
  FORGOT_PASSWORD_NAVIGATOR = 'FORGOT_PASSWORD_SCREEN_NAVIGATOR',
  MAIN_GAME_NAVIGATOR = 'MAIN_GAME_NAVIGATOR',
}

export enum ECreateProfileScreen {
  ENTER_DISPLAY_NAME_SCREEN = 'ENTER_DISPLAY_NAME_SCREEN',
  CHOOSE_AVATAR_SCREEN = 'CHOOSE_AVATAR_SCREEN',
  CREATE_PROFILE_SUCCESS_SCREEN = 'CREATE_PROFILE_SUCCESS_SCREEN',
  PERMISSION_LOCATION_SCREEN = 'PERMISSION_LOCATION_SCREEN',
}

export enum EForgotPasswordScreen {
  INPUT_PHONE_NUMBER_SCREEN = 'INPUT_PHONE_NUMBER_SCREEN',
  INPUT_NEW_PASSWORD_SCREEN = 'INPUT_NEW_PASSWORD_SCREEN',
}

export enum EMainGameScreen {
  MAP_SCREEN = 'MAP_SCREEN',
  MAP_TYPE_SCREEN = 'MAP_TYPE_SCREEN',
}
