import { ParamListBase } from '@react-navigation/native';
import { IPopupModalProps } from 'App/containers/Modal/PopupModal';
import { IRealtimeLocation } from 'App/types';
import { IResponseTerryCheckins, ITerryResponseDto, Location } from 'App/types/terry';

export enum ENavigationScreen {
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  ONBOARDING_SCREEN = 'ONBOARDING_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN',
  REGISTER_SCREEN = 'REGISTER_SCREEN',
  OTP_SCREEN = 'OTP_SCREEN',
  LOADING_MODAL = 'LOADING_MODAL',
  CREATE_PROFILE_NAVIGATOR = 'CREATE_PROFILE_NAVIGATOR',
  FORGOT_PASSWORD_NAVIGATOR = 'FORGOT_PASSWORD_SCREEN_NAVIGATOR',
  MAIN_GAME_NAVIGATOR = 'MAIN_GAME_NAVIGATOR',
  NETWORK_LOGGER_SCREEN = 'NETWORK_LOGGER_SCREEN',
  POPUP_SCREEN = 'POPUP_SCREEN',
}

export enum ECreateProfileScreen {
  ENTER_DISPLAY_NAME_SCREEN = 'ENTER_DISPLAY_NAME_SCREEN',
  CHOOSE_AVATAR_SCREEN = 'CHOOSE_AVATAR_SCREEN',
  CREATE_PROFILE_SUCCESS_SCREEN = 'CREATE_PROFILE_SUCCESS_SCREEN',
  PERMISSION_LOCATION_SCREEN = 'PERMISSION_LOCATION_SCREEN',
  PERMISSION_NOTIFICATION_SCREEN = 'PERMISSION_NOTIFICATION_SCREEN',
}

export enum EForgotPasswordScreen {
  INPUT_PHONE_NUMBER_SCREEN = 'INPUT_PHONE_NUMBER_SCREEN',
  INPUT_NEW_PASSWORD_SCREEN = 'INPUT_NEW_PASSWORD_SCREEN',
}

export enum EMainGameScreen {
  MAP_SCREEN = 'MAP_SCREEN',
  MAP_TYPE_SCREEN = 'MAP_TYPE_SCREEN',
  FILTER_SCREEN = 'FILTER_SCREEN',
  SETTING_NAVIGATOR = 'SETTING_NAVIGATOR',
  TERRY_DETAIL_SCREEN = 'TERRY_DETAIL_SCREEN',
  PROFILE_SCREEN = 'PROFILE_SCREEN',
  EDIT_PROFILE_SCREEN = 'EDIT_PROFILE_SCREEN',
  QR_SCREEN = 'QR_SCREEN',
  SCAN_PROFILE_QR_SCREEN = 'SCAN_PROFILE_QR_SCREEN',
  HISTORY = 'HISTORY',
  DETAIL_HISTORY = 'DETAIL_HISTORY',
  EDIT_DETAIL_HISTORY = 'EDIT_DETAIL_HISTORY',
  ENLARGE_IMAGE = 'ENLARGE_IMAGE',
  CREATE_NEW_TERRY_SCREEN = 'CREATE_NEW_TERRY_SCREEN',
  UPDATE_TERRY_SCREEN = 'UPDATE_TERRY_SCREEN',
  REVIEW_SCREEN = 'REVIEW_SCREEN',
  CHECKIN_TERRY_SCREEN = 'CHECKIN_TERRY_SCREEN',
  VERIFY_OFFICIAL_TERRY_SCREEN = 'VERIFY_OFFICIAL_TERRY_SCREEN',
  CHECKIN_TERRY_VOTE_SCREEN = 'CHECKIN_TERRY_VOTE_SCREEN',
  HUNTING_MAP_SCREEN = 'HUNTING_MAP_SCREEN',
  CHAT_SCREEN = 'CHAT_SCREEN',
  CHAT_VIEW_SCREEN = 'CHAT_VIEW_SCREEN',
}

export enum ESettingNavigator {
  MENU_SCREEN = 'MENU_SCREEN',
  UPGRADE_VERSION_SCREEN = 'UPGRADE_VERSION_SCREEN',
  RULE_SCREEN = 'RULE_SCREEN',
  LANGUAGE_SCREEN = 'LANGUAGE_SCREEN',
  PASSWORD_SCREEN = 'PASSWORD_SCREEN',
  LOW_ENERGY_SCREEN = 'LOW_ENERGY_SCREEN',
  POLICY_SCREEN = 'POLICY_SCREEN',
  ABOUT_SCREEN = 'ABOUT_SCREEN',
}
export interface EMainGameNavigatorParams extends ParamListBase {
  [EMainGameScreen.MAP_SCREEN]: { locationTerry?: IRealtimeLocation; terryId: string };
  [EMainGameScreen.EDIT_DETAIL_HISTORY]: IResponseTerryCheckins;
  [EMainGameScreen.MAP_TYPE_SCREEN]: undefined;
  [EMainGameScreen.FILTER_SCREEN]: undefined;
  [EMainGameScreen.SETTING_NAVIGATOR]: undefined;
  [EMainGameScreen.TERRY_DETAIL_SCREEN]: {
    userLocation?: Location;
    terry: ITerryResponseDto;
  };
  [EMainGameScreen.PROFILE_SCREEN]: undefined;
  [EMainGameScreen.EDIT_PROFILE_SCREEN]: undefined;
  [EMainGameScreen.QR_SCREEN]: undefined;
  [EMainGameScreen.HISTORY]: undefined;
  [EMainGameScreen.DETAIL_HISTORY]: IResponseTerryCheckins;
  [EMainGameScreen.REVIEW_SCREEN]: {
    terryId: string;
  };
  [EMainGameScreen.HUNTING_MAP_SCREEN]: {
    terry: ITerryResponseDto;
    userLocation: Location;
  };
  [ENavigationScreen.LOADING_MODAL]: undefined;
  [ENavigationScreen.POPUP_SCREEN]: IPopupModalProps;
  [EMainGameScreen.CHAT_SCREEN]: undefined;
  [EMainGameScreen.CHAT_VIEW_SCREEN]: {
    conversationId: string;
    recipientId?: string;
  };
  [EMainGameScreen.UPDATE_TERRY_SCREEN]: {
    terry: ITerryResponseDto;
  };
}

export interface ENavigatorParams extends ParamListBase {
  [ENavigationScreen.POPUP_SCREEN]: IPopupModalProps;
}

export enum EPopUpModalType {
  UNDEFINED_ERROR = 'UNDEFINED_ERROR',
  INVALID_ACCESS = 'INVALID_ACCESS',
  CANNOT_FOUND_PROFILE = 'CANNOT_FOUND_PROFILE',
  FOUND_PROFILE = 'FOUND_PROFILE',
  UPLOAD_FILE_FAILED = 'UPLOAD_FILE_FAILED',
  FILE_SIZE_NOT_VALID = 'FILE_SIZE_NOT_VALID',
  CANNOT_REFRESH_NOTIFICATION_TOKEN = 'CANNOT_REFRESH_NOTIFICATION_TOKEN',
  CANNOT_LOGIN = 'CANNOT_LOGIN',
  PROFILE_EXISTED = 'PROFILE_EXISTED',
  CANNOT_CREATE_QR_CODE = 'CANNOT_CREATE_QR_CODE',
  DISTANCE_ERROR = 'DISTANCE_ERROR',
  CREATE_TERRY_SUCCESS = 'CREATE_TERRY_SUCCESS',
  TERRY_INFORMATION_CAN_BE_DISCLOSED = 'TERRY_INFORMATION_CAN_BE_DISCLOSED',
  VERIFY_OFFICIAL_TERRY_FAILED = 'VERIFY_OFFICIAL_TERRY_FAILED',
  CONFIRM_DELETE_TERRY = 'CONFIRM_DELETE_TERRY',
  CONFIRM_SWITCH_ROLE = 'CONFIRM_SWITCH_ROLE',
}
