name: Code Quality
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - master

jobs:
  Code-Quality:
    name: Code quality
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Check lint and format
        run: |
          yarn lint:check
