import { KeyboardTypeOptions } from 'react-native';
import { ReturnKeyTypeOptions } from 'react-native';

export interface IInputProps {
  placeholder?: string;
  value?: string;
  helperText?: string;
  onChangeText?: (text: string) => void;
  secureTextEntry?: boolean;
  keyboardType?: KeyboardTypeOptions;
  customStyleContainer?: object;
  customStyleInput?: object;
  customStylePlaceholder?: object;
  customStyleError?: object;
  error?: string;
  onBlur?: () => void;
  onFocus?: () => void;
  onSubmitEditing?: () => void;
  returnKeyType?: ReturnKeyTypeOptions;
  autoCorrect?: boolean;
  autoFocus?: boolean;
  editable?: boolean;
  maxLength?: number;
  multiline?: boolean;
  numberOfLines?: number;
  placeholderTextColor?: string;
  label?: string;
  labelStyle?: object;
  labelContainerStyle?: object;
  isShowLabel?: boolean;
  isShowError?: boolean;
  isShowIcon?: boolean;
  icon?: any;
  iconStyle?: object;
  iconContainerStyle?: object;
  isShowClear?: boolean;
  clearIcon?: any;
  clearIconStyle?: object;
  isShowCalendarIcon?: boolean;
  calendarIcon?: any;
  calendarIconStyle?: object;
  calendarIconContainerStyle?: object;
  isShowClearIcon?: boolean;
  clearIconContainerStyle?: object;
  isShowErrorIcon?: boolean;
  errorIcon?: any;
  isShowEyeIcon?: boolean;
  eyeIcon?: any;
  eyeIconStyle?: object;
  eyeIconContainerStyle?: object;
  isShowEyeSplashIcon?: boolean;
  eyeSlashIcon?: any;
  eyeSlashIconStyle?: object;
  eyeSlashIconContainerStyle?: object;
  errorIconStyle?: object;
  errorIconContainerStyle?: object;
}
